export const data = [
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
    {
        Item_Code:"#FG01700",
        Item_Group:"Sagha WIP",
        Item_Category:"Laptop",
        Item_Name:"Sagha MUNASIBAT MIX",
        foreign_Name:"TEST",
        UoM:"Pieces",
        Barcode:"FGD02016",
        Retail_Price:"0",
        Sellable:"✓",
        non_:"0 0 0 0"
    },
]